name: Integration
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install WASM pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build in debug mode
        run: wasm-pack build --dev --target web --out-name package

      - name: Ensure proper formatting
        run: cargo fmt -- --check
